"""Merge reviewed HTTP workflow copy into the nine-language string catalog."""
import json
from pathlib import Path

LANGS = ['zh-Hans', 'zh-Hant', 'ja', 'fr', 'pt-BR', 'es', 'ko', 'de']
# English | Simplified Chinese | Traditional Chinese | Japanese | French | Portuguese | Spanish | Korean | German
ROWS = '''
Help|帮助|說明|ヘルプ|Aide|Ajuda|Ayuda|도움말|Hilfe
Attach the request files again before running.|请先重新选择请求附件，再运行。|請先重新選擇請求附件，再執行。|実行前にリクエストのファイルを選び直してください。|Sélectionnez à nouveau les fichiers de la requête avant l’exécution.|Anexe os arquivos da requisição novamente antes de executar.|Vuelva a adjuntar los archivos antes de ejecutar.|실행 전에 요청 파일을 다시 첨부하세요.|Fügen Sie die Anfragedateien vor der Ausführung erneut hinzu.
HTTP Workflows|HTTP 工作流|HTTP 工作流程|HTTP ワークフロー|Flux HTTP|Fluxos HTTP|Flujos HTTP|HTTP 워크플로|HTTP-Abläufe
Illustrated Guide|图文指南|圖文指南|図解ガイド|Guide illustré|Guia ilustrado|Guía ilustrada|그림 안내|Anleitung mit Beispielen
HTTP Workflow Guide|HTTP 工作流指南|HTTP 工作流程指南|HTTP ワークフローガイド|Guide des flux HTTP|Guia de fluxos HTTP|Guía de flujos HTTP|HTTP 워크플로 안내|Anleitung für HTTP-Abläufe
Variables & Checks|变量与检查|變數與檢查|変数とチェック|Variables et vérifications|Variáveis e verificações|Variables y comprobaciones|변수 및 검사|Variablen und Prüfungen
Compare Responses|响应对比|回應比較|レスポンスの比較|Comparer les réponses|Comparar respostas|Comparar respuestas|응답 비교|Antworten vergleichen
Run Requests|批量运行|批次執行|リクエストを順に実行|Exécuter les requêtes|Executar requisições|Ejecutar solicitudes|요청 일괄 실행|Anfragen ausführen
Rules are saved automatically.|规则会自动保存。|規則會自動儲存。|ルールは自動保存されます。|Les règles sont enregistrées automatiquement.|As regras são salvas automaticamente.|Las reglas se guardan automáticamente.|규칙은 자동으로 저장됩니다.|Regeln werden automatisch gespeichert.
Workflow|工作流|工作流程|ワークフロー|Flux|Fluxo|Flujo|워크플로|Ablauf
Guide|指南|指南|ガイド|Guide|Guia|Guía|안내|Anleitung
Response Variables|响应变量|回應變數|レスポンスから取得する変数|Variables de réponse|Variáveis da resposta|Variables de respuesta|응답 변수|Variablen aus Antworten
Add Response Variable|添加响应变量|新增回應變數|レスポンス変数を追加|Ajouter une variable de réponse|Adicionar variável da resposta|Añadir variable de respuesta|응답 변수 추가|Antwortvariable hinzufügen
Save Variables from Current Response|从当前响应保存变量|從目前回應儲存變數|現在のレスポンスから変数を保存|Enregistrer les variables de la réponse actuelle|Salvar variáveis da resposta atual|Guardar variables de la respuesta actual|현재 응답에서 변수 저장|Variablen aus aktueller Antwort speichern
Variables saved.|变量已保存。|變數已儲存。|変数を保存しました。|Variables enregistrées.|Variáveis salvas.|Variables guardadas.|변수를 저장했습니다.|Variablen gespeichert.
Response Checks|响应检查|回應檢查|レスポンスのチェック|Vérifications de réponse|Verificações da resposta|Comprobaciones de respuesta|응답 검사|Antwortprüfungen
Add Check|添加检查|新增檢查|チェックを追加|Ajouter une vérification|Adicionar verificação|Añadir comprobación|검사 추가|Prüfung hinzufügen
Check Current Response|检查当前响应|檢查目前回應|現在のレスポンスをチェック|Vérifier la réponse actuelle|Verificar resposta atual|Comprobar respuesta actual|현재 응답 검사|Aktuelle Antwort prüfen
Select an environment|选择环境|選擇環境|環境を選択|Choisir un environnement|Selecionar ambiente|Seleccionar entorno|환경 선택|Umgebung auswählen
Enabled|启用|啟用|有効|Activé|Ativado|Activado|사용|Aktiviert
Variable name|变量名称|變數名稱|変数名|Nom de variable|Nome da variável|Nombre de variable|변수 이름|Variablenname
Secret variable|敏感变量|敏感變數|機密変数|Variable confidentielle|Variável confidencial|Variable secreta|비밀 변수|Geheime Variable
Check|检查|檢查|チェック|Vérification|Verificação|Comprobación|검사|Prüfung
Status code equals|状态码等于|狀態碼等於|ステータスコードが一致|Code de statut égal à|Código de status igual a|Código de estado igual a|상태 코드 일치|Statuscode entspricht
JSON field equals|JSON 字段等于|JSON 欄位等於|JSON フィールドが一致|Champ JSON égal à|Campo JSON igual a|Campo JSON igual a|JSON 필드 일치|JSON-Feld entspricht
Response time below (ms)|响应耗时小于（毫秒）|回應時間小於（毫秒）|応答時間の上限（ms）|Temps de réponse inférieur à (ms)|Tempo de resposta abaixo de (ms)|Tiempo de respuesta inferior a (ms)|응답 시간 미만(ms)|Antwortzeit unter (ms)
Expected value|预期值|預期值|期待する値|Valeur attendue|Valor esperado|Valor esperado|예상 값|Erwarteter Wert
Response field|响应字段|回應欄位|レスポンスのフィールド|Champ de réponse|Campo da resposta|Campo de respuesta|응답 필드|Antwortfeld
Field path (for example /data/token)|字段路径（例如 /data/token）|欄位路徑（例如 /data/token）|フィールドのパス（例：/data/token）|Chemin du champ (ex. /data/token)|Caminho do campo (ex.: /data/token)|Ruta del campo (p. ej. /data/token)|필드 경로(예: /data/token)|Feldpfad (z. B. /data/token)
Baseline Response|基准响应|基準回應|基準レスポンス|Réponse de référence|Resposta de referência|Respuesta de referencia|기준 응답|Referenzantwort
Saved|保存时间|儲存時間|保存日時|Enregistrée le|Salva em|Guardada el|저장 시각|Gespeichert
Save Current Response as Baseline|将当前响应保存为基准|將目前回應儲存為基準|現在のレスポンスを基準として保存|Utiliser la réponse actuelle comme référence|Salvar resposta atual como referência|Guardar respuesta actual como referencia|현재 응답을 기준으로 저장|Aktuelle Antwort als Referenz speichern
Replace Baseline with Current Response|用当前响应替换基准|以目前回應取代基準|現在のレスポンスで基準を置き換え|Remplacer la référence par la réponse actuelle|Substituir referência pela resposta atual|Sustituir referencia por respuesta actual|현재 응답으로 기준 교체|Referenz durch aktuelle Antwort ersetzen
Ignored paths, separated by commas|忽略的路径，用逗号分隔|忽略的路徑，以逗號分隔|無視するパス（カンマ区切り）|Chemins ignorés, séparés par des virgules|Caminhos ignorados, separados por vírgulas|Rutas ignoradas, separadas por comas|무시할 경로, 쉼표로 구분|Ignorierte Pfade, durch Kommas getrennt
Ignored paths|忽略的路径|忽略的路徑|無視するパス|Chemins ignorés|Caminhos ignorados|Rutas ignoradas|무시할 경로|Ignorierte Pfade
Compare with Baseline|与基准对比|與基準比較|基準と比較|Comparer à la référence|Comparar com a referência|Comparar con la referencia|기준과 비교|Mit Referenz vergleichen
No differences.|没有差异。|沒有差異。|差分はありません。|Aucune différence.|Nenhuma diferença.|Sin diferencias.|차이가 없습니다.|Keine Unterschiede.
Execution Order|执行顺序|執行順序|実行順序|Ordre d’exécution|Ordem de execução|Orden de ejecución|실행 순서|Ausführungsreihenfolge
Folder|文件夹|資料夾|フォルダ|Dossier|Pasta|Carpeta|폴더|Ordner
All HTTP Requests|全部 HTTP 请求|所有 HTTP 請求|すべての HTTP リクエスト|Toutes les requêtes HTTP|Todas as requisições HTTP|Todas las solicitudes HTTP|모든 HTTP 요청|Alle HTTP-Anfragen
Stop on first failure|首次失败时停止|首次失敗時停止|最初の失敗で停止|Arrêter au premier échec|Parar na primeira falha|Detener al primer fallo|첫 실패 시 중지|Beim ersten Fehler anhalten
Stop Run|停止运行|停止執行|実行を停止|Arrêter l’exécution|Parar execução|Detener ejecución|실행 중지|Ausführung stoppen
Run Selected Requests|运行选中请求|執行所選請求|選択したリクエストを実行|Exécuter les requêtes sélectionnées|Executar requisições selecionadas|Ejecutar solicitudes seleccionadas|선택한 요청 실행|Ausgewählte Anfragen ausführen
Run Results|运行结果|執行結果|実行結果|Résultats|Resultados da execução|Resultados de ejecución|실행 결과|Ergebnisse
Move Up|上移|上移|上へ移動|Monter|Mover para cima|Subir|위로 이동|Nach oben
Move Down|下移|下移|下へ移動|Descendre|Mover para baixo|Bajar|아래로 이동|Nach unten
Send the login request|发送登录请求|傳送登入請求|ログインリクエストを送信|Envoyer la requête de connexion|Enviar requisição de login|Enviar solicitud de inicio de sesión|로그인 요청 보내기|Anmeldeanfrage senden
Choose the field and variable|选择字段并命名变量|選擇欄位並命名變數|フィールドと変数を選択|Choisir le champ et la variable|Escolher campo e variável|Elegir campo y variable|필드와 변수 선택|Feld und Variable auswählen
Reuse it in the next request|在下一个请求中使用|在下一個請求中使用|次のリクエストで利用|Réutiliser dans la requête suivante|Reutilizar na próxima requisição|Reutilizar en la siguiente solicitud|다음 요청에서 재사용|In der nächsten Anfrage verwenden
Authentication|认证|驗證|認証|Authentification|Autenticação|Autenticación|인증|Authentifizierung
Save a known response|保存一份已确认的响应|儲存已確認的回應|確認済みのレスポンスを保存|Enregistrer une réponse connue|Salvar uma resposta conhecida|Guardar una respuesta conocida|확인된 응답 저장|Bekannte Antwort speichern
Send again and compare|再次发送并对比|再次傳送並比較|再送信して比較|Renvoyer et comparer|Enviar novamente e comparar|Enviar de nuevo y comparar|다시 보내고 비교|Erneut senden und vergleichen
Ignore changing fields|忽略动态字段|忽略變動欄位|変動するフィールドを除外|Ignorer les champs variables|Ignorar campos que mudam|Ignorar campos cambiantes|변하는 필드 무시|Veränderliche Felder ignorieren
Add checks to each request|为每个请求添加检查|為每個請求新增檢查|各リクエストにチェックを追加|Ajouter des vérifications à chaque requête|Adicionar verificações a cada requisição|Añadir comprobaciones a cada solicitud|각 요청에 검사 추가|Jeder Anfrage Prüfungen hinzufügen
Select and order requests|选择请求并调整顺序|選擇請求並調整順序|リクエストを選択して並べ替え|Choisir et ordonner les requêtes|Selecionar e ordenar requisições|Seleccionar y ordenar solicitudes|요청 선택 및 순서 지정|Anfragen auswählen und sortieren
Run and inspect results|运行并查看结果|執行並檢視結果|実行して結果を確認|Exécuter et examiner les résultats|Executar e analisar resultados|Ejecutar y revisar resultados|실행 후 결과 확인|Ausführen und Ergebnisse prüfen
JSON tools support responses up to 1 MB.|JSON 工具支持最大 1 MB 的响应。|JSON 工具支援最大 1 MB 的回應。|JSON ツールは 1 MB 以下のレスポンスに対応します。|Les outils JSON acceptent des réponses jusqu’à 1 Mo.|As ferramentas JSON aceitam respostas de até 1 MB.|Las herramientas JSON admiten respuestas de hasta 1 MB.|JSON 도구는 최대 1 MB 응답을 지원합니다.|JSON-Werkzeuge unterstützen Antworten bis 1 MB.
The response is not valid JSON.|响应不是有效的 JSON。|回應不是有效的 JSON。|レスポンスは有効な JSON ではありません。|La réponse n’est pas un JSON valide.|A resposta não é um JSON válido.|La respuesta no es un JSON válido.|응답이 유효한 JSON이 아닙니다.|Die Antwort ist kein gültiges JSON.
JSON field not found:|找不到 JSON 字段：|找不到 JSON 欄位：|JSON フィールドが見つかりません：|Champ JSON introuvable :|Campo JSON não encontrado:|Campo JSON no encontrado:|JSON 필드를 찾을 수 없습니다:|JSON-Feld nicht gefunden:
A field path must start with /, for example /data/token.|字段路径必须以 / 开头，例如 /data/token。|欄位路徑必須以 / 開頭，例如 /data/token。|パスは / で始めてください。例：/data/token。|Un chemin doit commencer par /, par exemple /data/token.|O caminho deve começar com /, como /data/token.|La ruta debe comenzar con /, por ejemplo /data/token.|필드 경로는 /로 시작해야 합니다. 예: /data/token.|Ein Feldpfad muss mit / beginnen, z. B. /data/token.
This JSON is too complex to display. Choose a smaller response.|此 JSON 结构过于复杂，请选择更小的响应。|此 JSON 結構過於複雜，請選擇較小的回應。|JSON が複雑すぎます。より小さいレスポンスを選んでください。|Ce JSON est trop complexe. Choisissez une réponse plus petite.|Este JSON é complexo demais. Escolha uma resposta menor.|Este JSON es demasiado complejo. Elija una respuesta más pequeña.|JSON이 너무 복잡합니다. 더 작은 응답을 선택하세요.|Dieses JSON ist zu komplex. Wählen Sie eine kleinere Antwort.
Select an environment before saving response variables.|保存响应变量前，请先选择环境。|儲存回應變數前，請先選擇環境。|変数を保存する前に環境を選択してください。|Choisissez un environnement avant d’enregistrer les variables.|Selecione um ambiente antes de salvar as variáveis.|Seleccione un entorno antes de guardar las variables.|응답 변수를 저장하기 전에 환경을 선택하세요.|Wählen Sie vor dem Speichern eine Umgebung aus.
Use unique, nonempty variable names without braces.|变量名不能为空或重复，也不能包含花括号。|變數名稱不能空白或重複，也不能包含大括號。|変数名は空欄や重複を避け、中括弧を含めないでください。|Utilisez des noms uniques, non vides et sans accolades.|Use nomes únicos, não vazios e sem chaves.|Use nombres únicos, no vacíos y sin llaves.|변수 이름은 비어 있거나 중복될 수 없으며 중괄호를 포함하면 안 됩니다.|Verwenden Sie eindeutige, nicht leere Namen ohne geschweifte Klammern.
The selected field is null. Existing variables were kept.|所选字段为 null，已保留现有变量。|所選欄位為 null，已保留現有變數。|選択したフィールドは null です。既存の変数を保持しました。|Le champ sélectionné est null. Les variables existantes sont conservées.|O campo é null. As variáveis existentes foram mantidas.|El campo es null. Se conservaron las variables existentes.|선택한 필드가 null입니다. 기존 변수를 유지했습니다.|Das Feld ist null. Bestehende Variablen wurden beibehalten.
The selected environment no longer exists.|所选环境已不存在。|所選環境已不存在。|選択した環境は存在しません。|L’environnement sélectionné n’existe plus.|O ambiente selecionado não existe mais.|El entorno seleccionado ya no existe.|선택한 환경이 더 이상 존재하지 않습니다.|Die ausgewählte Umgebung existiert nicht mehr.
This request is already running.|此请求正在运行。|此請求正在執行。|このリクエストは実行中です。|Cette requête est déjà en cours.|Esta requisição já está em execução.|Esta solicitud ya se está ejecutando.|이 요청은 이미 실행 중입니다.|Diese Anfrage wird bereits ausgeführt.
Response variables, comparisons, and batch runs|响应变量、对比与批量运行|回應變數、比較與批次執行|レスポンス変数、比較、一括実行|Variables, comparaisons et exécutions groupées|Variáveis, comparações e execuções em lote|Variables, comparaciones y ejecución por lotes|응답 변수, 비교 및 일괄 실행|Antwortvariablen, Vergleiche und Stapelausführung
'''

ROWS += '''
Choose a response field, name a variable, then use {{name}} in another request.|选择响应字段并命名变量，然后在其他请求中使用 {{name}}。|選擇回應欄位並命名變數，再於其他請求中使用 {{name}}。|レスポンスのフィールドに変数名を付け、別のリクエストで {{name}} を使います。|Choisissez un champ, nommez une variable, puis utilisez {{name}} dans une autre requête.|Escolha um campo, nomeie uma variável e use {{name}} em outra requisição.|Elija un campo, nombre una variable y use {{name}} en otra solicitud.|응답 필드를 선택하고 변수 이름을 지정한 뒤 다른 요청에서 {{name}}을 사용하세요.|Wählen Sie ein Antwortfeld, benennen Sie eine Variable und verwenden Sie {{name}} in einer anderen Anfrage.
Enabled extraction rules run after each successful HTTP response. Existing variables with the same name are replaced.|启用的提取规则会在每次 HTTP 成功响应后执行，同名变量会被覆盖。|啟用的擷取規則會在每次 HTTP 成功回應後執行，同名變數會被覆寫。|有効なルールは HTTP の成功レスポンスごとに実行され、同名の変数を更新します。|Les règles actives s’appliquent après chaque réponse HTTP réussie et remplacent les variables de même nom.|As regras ativas são aplicadas após cada resposta HTTP bem-sucedida e substituem variáveis com o mesmo nome.|Las reglas activas se aplican tras cada respuesta HTTP correcta y sustituyen variables con el mismo nombre.|활성 규칙은 성공한 HTTP 응답마다 실행되며 같은 이름의 변수를 덮어씁니다.|Aktive Regeln werden nach jeder erfolgreichen HTTP-Antwort ausgeführt und ersetzen gleichnamige Variablen.
Save a response as a baseline. Send again, then compare JSON fields and the HTTP status.|保存一份响应作为基准，再次发送后对比 JSON 字段与 HTTP 状态码。|儲存一份回應作為基準，再次傳送後比較 JSON 欄位與 HTTP 狀態碼。|レスポンスを基準として保存し、再送信後に JSON フィールドと HTTP ステータスを比較します。|Enregistrez une réponse comme référence, renvoyez la requête et comparez les champs JSON et le statut HTTP.|Salve uma resposta como referência, envie novamente e compare os campos JSON e o status HTTP.|Guarde una respuesta como referencia, envíe de nuevo y compare campos JSON y estado HTTP.|응답을 기준으로 저장한 후 다시 보내 JSON 필드와 HTTP 상태를 비교하세요.|Speichern Sie eine Antwort als Referenz, senden Sie erneut und vergleichen Sie JSON-Felder und HTTP-Status.
The baseline is stored on this device and may contain response data.|基准保存在此设备上，可能包含响应中的数据。|基準儲存在此裝置上，可能包含回應中的資料。|基準はこのデバイスに保存され、レスポンスのデータを含む場合があります。|La référence est stockée sur cet appareil et peut contenir des données de réponse.|A referência fica neste dispositivo e pode conter dados da resposta.|La referencia se guarda en este dispositivo y puede contener datos de respuesta.|기준은 이 기기에 저장되며 응답 데이터를 포함할 수 있습니다.|Die Referenz wird auf diesem Gerät gespeichert und kann Antwortdaten enthalten.
Example: /timestamp, /requestId. A path also ignores all fields below it.|例如 /timestamp, /requestId。指定路径也会忽略其下所有字段。|例如 /timestamp, /requestId。指定路徑也會忽略其下所有欄位。|例：/timestamp, /requestId。指定したパスの配下もすべて除外します。|Exemple : /timestamp, /requestId. Les champs sous ces chemins sont aussi ignorés.|Exemplo: /timestamp, /requestId. Os campos abaixo de cada caminho também são ignorados.|Ejemplo: /timestamp, /requestId. También se omiten los campos bajo cada ruta.|예: /timestamp, /requestId. 경로 아래의 모든 필드도 무시됩니다.|Beispiel: /timestamp, /requestId. Untergeordnete Felder werden ebenfalls ignoriert.
Requests run one at a time in the order below. Extracted variables are available to the next request.|请求按以下顺序逐个执行，提取的变量可用于下一个请求。|請求依以下順序逐一執行，擷取的變數可用於下一個請求。|以下の順序で一つずつ実行します。取得した変数は次のリクエストで使えます。|Les requêtes s’exécutent une à une dans cet ordre. Les variables extraites sont disponibles pour la suivante.|As requisições são executadas uma por vez nesta ordem. As variáveis extraídas ficam disponíveis para a próxima.|Las solicitudes se ejecutan una a una en este orden. Las variables extraídas están disponibles para la siguiente.|아래 순서대로 하나씩 실행됩니다. 추출된 변수는 다음 요청에서 사용할 수 있습니다.|Anfragen laufen einzeln in dieser Reihenfolge. Extrahierte Variablen stehen der nächsten Anfrage zur Verfügung.
Run sends real requests, including POST and DELETE. Review the selected requests and active environment first.|运行会真实发送请求，包括 POST 和 DELETE。请先核对选中的请求和当前环境。|執行會實際傳送請求，包括 POST 和 DELETE。請先確認所選請求和目前環境。|POST や DELETE も実際に送信します。選択したリクエストと環境を先に確認してください。|L’exécution envoie de vraies requêtes, dont POST et DELETE. Vérifiez d’abord la sélection et l’environnement actif.|A execução envia requisições reais, incluindo POST e DELETE. Confira a seleção e o ambiente ativo antes.|La ejecución envía solicitudes reales, incluidas POST y DELETE. Revise primero la selección y el entorno activo.|POST와 DELETE를 포함한 실제 요청을 보냅니다. 선택한 요청과 활성 환경을 먼저 확인하세요.|Es werden echte Anfragen gesendet, auch POST und DELETE. Prüfen Sie vorher die Auswahl und die aktive Umgebung.
Run stopped. A request already sent may still complete on the server.|运行已停止，已发送的请求仍可能在服务器上完成。|執行已停止，已傳送的請求仍可能在伺服器上完成。|実行を停止しました。送信済みのリクエストはサーバーで完了する場合があります。|Exécution arrêtée. Une requête déjà envoyée peut encore aboutir sur le serveur.|Execução interrompida. Uma requisição já enviada ainda pode ser concluída no servidor.|Ejecución detenida. Una solicitud ya enviada aún puede completarse en el servidor.|실행이 중지되었습니다. 이미 보낸 요청은 서버에서 완료될 수 있습니다.|Ausführung angehalten. Eine bereits gesendete Anfrage kann auf dem Server noch abgeschlossen werden.
Open an HTTP request and tap the flowchart button in the toolbar to open HTTP Workflows.|打开 HTTP 请求，点击工具栏中的流程图按钮，进入“HTTP 工作流”。|開啟 HTTP 請求，點按工具列的流程圖按鈕，進入「HTTP 工作流程」。|HTTP リクエストを開き、ツールバーのフローチャートボタンから HTTP ワークフローを開きます。|Ouvrez une requête HTTP, puis utilisez le bouton de diagramme de la barre d’outils pour ouvrir Flux HTTP.|Abra uma requisição HTTP e use o botão de fluxograma na barra de ferramentas para abrir Fluxos HTTP.|Abra una solicitud HTTP y pulse el botón de diagrama de la barra para abrir Flujos HTTP.|HTTP 요청을 열고 도구 모음의 순서도 버튼을 눌러 HTTP 워크플로를 여세요.|Öffnen Sie eine HTTP-Anfrage und klicken Sie auf das Ablaufdiagramm in der Werkzeugleiste, um HTTP-Abläufe zu öffnen.
Select your test environment, then send a login request. The response must contain a JSON value such as a token.|选择测试环境并发送登录请求，响应中需要包含 token 等 JSON 值。|選擇測試環境並傳送登入請求，回應中需包含 token 等 JSON 值。|テスト環境を選んでログインリクエストを送信します。レスポンスには token などの JSON 値が必要です。|Choisissez votre environnement de test et envoyez une requête de connexion. La réponse doit contenir une valeur JSON, par exemple un token.|Selecione o ambiente de teste e envie uma requisição de login. A resposta deve conter um valor JSON, como um token.|Seleccione el entorno de prueba y envíe una solicitud de inicio de sesión. La respuesta debe contener un valor JSON, como un token.|테스트 환경을 선택하고 로그인 요청을 보내세요. 응답에 token 같은 JSON 값이 있어야 합니다.|Wählen Sie die Testumgebung und senden Sie eine Anmeldeanfrage. Die Antwort muss einen JSON-Wert wie ein Token enthalten.
In Variables & Checks, tap Add Response Variable. Choose /data/token, enter token as the variable name, and leave Secret variable enabled. Tap Save Variables from Current Response.|在“变量与检查”中点击“添加响应变量”，选择 /data/token，变量名填 token，并保持“敏感变量”启用。点击“从当前响应保存变量”。|在「變數與檢查」點按「新增回應變數」，選擇 /data/token，變數名稱填 token，並保持「敏感變數」啟用。點按「從目前回應儲存變數」。|「変数とチェック」で「レスポンス変数を追加」を選びます。/data/token を選択し、変数名を token にして「機密変数」を有効にします。「現在のレスポンスから変数を保存」を押します。|Dans Variables et vérifications, ajoutez une variable de réponse. Choisissez /data/token, nommez-la token et gardez Variable confidentielle activée. Enregistrez les variables de la réponse actuelle.|Em Variáveis e verificações, adicione uma variável da resposta. Escolha /data/token, use token como nome e mantenha Variável confidencial ativada. Salve as variáveis da resposta atual.|En Variables y comprobaciones, añada una variable de respuesta. Elija /data/token, use token como nombre y mantenga Variable secreta activada. Guarde las variables de la respuesta actual.|변수 및 검사에서 응답 변수 추가를 누르세요. /data/token을 선택하고 변수 이름에 token을 입력한 뒤 비밀 변수를 켜 두세요. 현재 응답에서 변수 저장을 누르세요.|Fügen Sie unter Variablen und Prüfungen eine Antwortvariable hinzu. Wählen Sie /data/token, nennen Sie die Variable token und aktivieren Sie Geheime Variable. Speichern Sie die Variablen aus der aktuellen Antwort.
In another request in the same project, choose Bearer Token authentication and enter {{token}}. Send with the same environment selected. Enabled rules also save new values automatically after future 2xx responses.|在同项目的另一个请求中选择 Bearer Token 认证，填入 {{token}}，使用同一环境发送。之后每次返回 2xx，启用的规则也会自动保存新值。|在同專案的另一個請求中選擇 Bearer Token 驗證，填入 {{token}}，使用相同環境傳送。之後每次回傳 2xx，啟用的規則也會自動儲存新值。|同じプロジェクトの別のリクエストで Bearer Token 認証を選び、{{token}} を入力します。同じ環境で送信してください。有効なルールは以後の 2xx レスポンスでも自動保存します。|Dans une autre requête du même projet, choisissez Bearer Token et saisissez {{token}}. Envoyez avec le même environnement. Les règles actives enregistrent aussi les nouvelles valeurs après les réponses 2xx.|Em outra requisição do mesmo projeto, escolha Bearer Token e insira {{token}}. Envie no mesmo ambiente. As regras ativas também salvam novos valores após respostas 2xx.|En otra solicitud del mismo proyecto, elija Bearer Token e introduzca {{token}}. Envíe con el mismo entorno. Las reglas activas también guardan nuevos valores tras respuestas 2xx.|같은 프로젝트의 다른 요청에서 Bearer Token 인증을 선택하고 {{token}}을 입력하세요. 같은 환경으로 보내세요. 활성 규칙은 이후 2xx 응답에서도 새 값을 자동 저장합니다.|Wählen Sie in einer anderen Anfrage desselben Projekts Bearer Token und geben Sie {{token}} ein. Senden Sie mit derselben Umgebung. Aktive Regeln speichern nach weiteren 2xx-Antworten automatisch neue Werte.
Extraction is all-or-nothing. A missing or null field keeps every existing variable unchanged. Secret variables follow the existing environment storage behavior.|提取必须全部成功才会保存。字段缺失或为 null 时，所有现有变量都保持不变。敏感变量沿用现有的环境存储方式。|擷取必須全部成功才會儲存。欄位缺少或為 null 時，所有現有變數都保持不變。敏感變數沿用現有的環境儲存方式。|すべての取得に成功した場合だけ保存します。フィールドがないか null の場合、既存の変数は変更しません。機密変数は従来の環境変数と同じ方法で保存します。|L’extraction est atomique. Un champ manquant ou null laisse toutes les variables intactes. Les variables confidentielles utilisent le stockage habituel des environnements.|A extração só salva se todos os campos forem válidos. Campos ausentes ou null mantêm todas as variáveis. Variáveis confidenciais usam o armazenamento de ambientes existente.|La extracción solo guarda si todos los campos son válidos. Un campo ausente o null conserva todas las variables. Las variables secretas usan el almacenamiento de entornos existente.|모든 추출이 성공해야 저장됩니다. 필드가 없거나 null이면 모든 기존 변수를 유지합니다. 비밀 변수는 기존 환경 저장 방식을 따릅니다.|Extraktionen werden nur vollständig gespeichert. Bei fehlenden oder null-Feldern bleiben alle Variablen unverändert. Geheime Variablen nutzen die bestehende Umgebungsspeicherung.
Send a request and open Compare Responses. Tap Save Current Response as Baseline. This JSON response stays on this device, including after restarting the app.|发送请求，打开“响应对比”，点击“将当前响应保存为基准”。这份 JSON 响应保存在本设备，重启程序后仍可使用。|傳送請求，開啟「回應比較」，點按「將目前回應儲存為基準」。這份 JSON 回應儲存在本裝置，重新啟動程式後仍可使用。|送信後に「レスポンスの比較」を開き、「現在のレスポンスを基準として保存」を押します。JSON レスポンスはアプリを再起動してもこのデバイスに残ります。|Envoyez une requête, ouvrez Comparer les réponses et enregistrez la réponse actuelle comme référence. Ce JSON reste sur cet appareil, même après un redémarrage.|Envie uma requisição, abra Comparar respostas e salve a resposta atual como referência. Esse JSON permanece no dispositivo após reiniciar o app.|Envíe una solicitud, abra Comparar respuestas y guarde la respuesta actual como referencia. Este JSON permanece en el dispositivo tras reiniciar la app.|요청을 보낸 뒤 응답 비교를 열고 현재 응답을 기준으로 저장을 누르세요. 이 JSON 응답은 앱을 다시 시작해도 기기에 남습니다.|Senden Sie eine Anfrage, öffnen Sie Antworten vergleichen und speichern Sie die aktuelle Antwort als Referenz. Dieses JSON bleibt auch nach einem Neustart auf dem Gerät.
Close the workflow panel, change the request or environment, and send again. Reopen Compare Responses and tap Compare with Baseline. Red shows the old value; green shows the new value.|关闭工作流面板，修改请求或切换环境后再次发送。重新打开“响应对比”，点击“与基准对比”。红色显示旧值，绿色显示新值。|關閉工作流程面板，修改請求或切換環境後再次傳送。重新開啟「回應比較」，點按「與基準比較」。紅色顯示舊值，綠色顯示新值。|パネルを閉じ、リクエストや環境を変更して再送信します。「レスポンスの比較」を開き直し、「基準と比較」を押します。赤は旧値、緑は新値です。|Fermez le panneau, modifiez la requête ou l’environnement et renvoyez. Rouvrez Comparer les réponses et comparez à la référence. Le rouge montre l’ancienne valeur, le vert la nouvelle.|Feche o painel, altere a requisição ou o ambiente e envie novamente. Reabra Comparar respostas e compare com a referência. Vermelho mostra o valor antigo; verde, o novo.|Cierre el panel, cambie la solicitud o el entorno y envíe de nuevo. Reabra Comparar respuestas y compare con la referencia. Rojo indica el valor anterior; verde, el nuevo.|패널을 닫고 요청이나 환경을 바꾼 뒤 다시 보내세요. 응답 비교를 다시 열고 기준과 비교를 누르세요. 빨간색은 이전 값, 초록색은 새 값입니다.|Schließen Sie das Fenster, ändern Sie Anfrage oder Umgebung und senden Sie erneut. Öffnen Sie Antworten vergleichen und vergleichen Sie mit der Referenz. Rot zeigt den alten Wert, Grün den neuen.
Enter /timestamp, /requestId in Ignored paths to skip values that change every time. A path also skips nested fields. Arrays are compared by position. Replace the baseline only when you want a new reference.|在“忽略的路径”中填入 /timestamp, /requestId，跳过每次变化的值及其下级字段。数组按位置对比。只有需要新参考时才替换基准。|在「忽略的路徑」填入 /timestamp, /requestId，略過每次變動的值及其下層欄位。陣列依位置比較。只有需要新參考時才取代基準。|「無視するパス」に /timestamp, /requestId を入力すると、変動する値と配下のフィールドを除外します。配列は位置で比較します。新しい基準が必要なときだけ置き換えてください。|Saisissez /timestamp, /requestId dans Chemins ignorés pour exclure les valeurs variables et leurs champs imbriqués. Les tableaux sont comparés par position. Remplacez la référence seulement pour en définir une nouvelle.|Insira /timestamp, /requestId em Caminhos ignorados para excluir valores que mudam e seus campos internos. Arrays são comparados por posição. Substitua a referência apenas quando precisar de uma nova.|Introduzca /timestamp, /requestId en Rutas ignoradas para omitir valores cambiantes y campos anidados. Los arrays se comparan por posición. Sustituya la referencia solo cuando necesite una nueva.|무시할 경로에 /timestamp, /requestId를 입력하면 매번 바뀌는 값과 하위 필드를 제외합니다. 배열은 위치별로 비교합니다. 새 기준이 필요할 때만 교체하세요.|Geben Sie unter Ignorierte Pfade /timestamp, /requestId ein, um wechselnde Werte und untergeordnete Felder auszuschließen. Arrays werden nach Position verglichen. Ersetzen Sie die Referenz nur bei Bedarf.
JSON tools support responses up to 1 MB. This comparison checks JSON fields and HTTP status; it does not compare response headers or timing.|JSON 工具支持最大 1 MB 的响应。本功能对比 JSON 字段和 HTTP 状态码，不对比响应头或耗时。|JSON 工具支援最大 1 MB 的回應。本功能比較 JSON 欄位和 HTTP 狀態碼，不比較回應標頭或時間。|JSON ツールは 1 MB 以下に対応します。比較対象は JSON フィールドと HTTP ステータスで、ヘッダーや時間は含みません。|Les outils JSON acceptent jusqu’à 1 Mo. La comparaison porte sur les champs JSON et le statut HTTP, sans les en-têtes ni la durée.|As ferramentas JSON aceitam até 1 MB. A comparação verifica campos JSON e status HTTP, sem comparar cabeçalhos ou tempo.|Las herramientas JSON admiten hasta 1 MB. Se comparan campos JSON y estado HTTP, sin cabeceras ni tiempos.|JSON 도구는 최대 1 MB를 지원합니다. JSON 필드와 HTTP 상태를 비교하며 응답 헤더와 시간은 비교하지 않습니다.|JSON-Werkzeuge unterstützen bis 1 MB. Verglichen werden JSON-Felder und HTTP-Status, keine Antwortheader oder Zeiten.
In Variables & Checks, tap Add Check. Choose a status code, a JSON field value, or a response time limit. Enter an expected value, then use Check Current Response to try it. For JSON strings, enter the text without quotation marks.|在“变量与检查”中点击“添加检查”，选择状态码、JSON 字段值或耗时上限，填写预期值，再用“检查当前响应”试运行。JSON 字符串直接填文本，不加引号。|在「變數與檢查」點按「新增檢查」，選擇狀態碼、JSON 欄位值或時間上限，填入預期值，再用「檢查目前回應」試跑。JSON 字串直接填文字，不加引號。|「変数とチェック」でチェックを追加し、ステータスコード、JSON 値、応答時間を選びます。期待値を入力し、「現在のレスポンスをチェック」で試します。JSON 文字列は引用符なしで入力します。|Ajoutez une vérification dans Variables et vérifications. Choisissez un code de statut, une valeur JSON ou une durée maximale. Saisissez la valeur attendue et vérifiez la réponse actuelle. Entrez les chaînes JSON sans guillemets.|Adicione uma verificação em Variáveis e verificações. Escolha código de status, valor JSON ou limite de tempo. Insira o valor esperado e verifique a resposta atual. Para strings JSON, digite sem aspas.|Añada una comprobación en Variables y comprobaciones. Elija código de estado, valor JSON o límite de tiempo. Introduzca el valor esperado y compruebe la respuesta actual. Escriba cadenas JSON sin comillas.|변수 및 검사에서 검사를 추가하세요. 상태 코드, JSON 값, 시간 제한을 선택하고 예상 값을 입력한 뒤 현재 응답 검사로 확인하세요. JSON 문자열은 따옴표 없이 입력하세요.|Fügen Sie unter Variablen und Prüfungen eine Prüfung hinzu. Wählen Sie Statuscode, JSON-Wert oder Zeitlimit. Geben Sie den erwarteten Wert ein und prüfen Sie die aktuelle Antwort. JSON-Zeichenfolgen ohne Anführungszeichen eingeben.
Open Run Requests. Choose a folder or all HTTP requests, uncheck requests to skip, and use the arrows to put login before requests that need its token. Keep Stop on first failure enabled while setting up.|打开“批量运行”，选择文件夹或全部 HTTP 请求，取消勾选要跳过的请求，用箭头把登录放到需要 token 的请求前。配置时建议启用“首次失败时停止”。|開啟「批次執行」，選擇資料夾或所有 HTTP 請求，取消勾選要略過的請求，用箭頭把登入放在需要 token 的請求之前。設定時建議啟用「首次失敗時停止」。|「リクエストを順に実行」を開き、フォルダまたは全 HTTP を選びます。不要な項目を外し、矢印でログインを token を使うリクエストより前に置きます。設定時は「最初の失敗で停止」を有効にします。|Ouvrez Exécuter les requêtes, choisissez un dossier ou toutes les requêtes HTTP et décochez celles à ignorer. Placez la connexion avant les requêtes utilisant son token avec les flèches. Gardez l’arrêt au premier échec pendant la configuration.|Abra Executar requisições, escolha uma pasta ou todas as requisições HTTP e desmarque as que deseja pular. Use as setas para colocar o login antes das requisições que usam o token. Mantenha Parar na primeira falha durante a configuração.|Abra Ejecutar solicitudes, elija una carpeta o todas las solicitudes HTTP y desmarque las que quiera omitir. Use las flechas para situar el inicio de sesión antes de las solicitudes que necesitan el token. Mantenga Detener al primer fallo al configurar.|요청 일괄 실행에서 폴더나 모든 HTTP 요청을 선택하고 건너뛸 요청을 해제하세요. 화살표로 로그인을 token이 필요한 요청 앞에 두세요. 설정 중에는 첫 실패 시 중지를 켜 두세요.|Öffnen Sie Anfragen ausführen, wählen Sie einen Ordner oder alle HTTP-Anfragen und deaktivieren Sie übersprungene Anfragen. Verschieben Sie die Anmeldung mit den Pfeilen vor Anfragen, die ihr Token benötigen. Lassen Sie Beim ersten Fehler anhalten während der Einrichtung aktiv.
Review the active environment and tap Run Selected Requests. The runner sends real requests one at a time. Each result shows HTTP status, duration, and checks. Network errors, extraction errors, failed checks, and non-2xx responses count as failures.|核对当前环境后，点击“运行选中请求”。请求会逐个真实发送，结果显示 HTTP 状态码、耗时和检查结果。网络错误、提取错误、检查不通过和非 2xx 响应都算失败。|確認目前環境後，點按「執行所選請求」。請求會逐一實際傳送，結果顯示 HTTP 狀態碼、時間和檢查結果。網路錯誤、擷取錯誤、檢查未通過和非 2xx 回應都算失敗。|環境を確認し、選択したリクエストを実行します。実際のリクエストを一つずつ送信し、HTTP ステータス、時間、チェック結果を表示します。通信・取得エラー、チェック不合格、2xx 以外は失敗です。|Vérifiez l’environnement et exécutez les requêtes sélectionnées. Elles sont réellement envoyées une à une. Chaque résultat affiche statut HTTP, durée et vérifications. Erreurs réseau, d’extraction, vérifications échouées et réponses hors 2xx sont des échecs.|Confira o ambiente e execute as requisições selecionadas. Elas são enviadas de verdade, uma por vez. Cada resultado mostra status HTTP, duração e verificações. Erros de rede ou extração, verificações reprovadas e respostas fora de 2xx contam como falhas.|Revise el entorno y ejecute las solicitudes seleccionadas. Se envían solicitudes reales una a una. Cada resultado muestra estado HTTP, duración y comprobaciones. Errores de red o extracción, comprobaciones fallidas y respuestas fuera de 2xx cuentan como fallos.|환경을 확인하고 선택한 요청 실행을 누르세요. 실제 요청을 하나씩 보내며 결과에 HTTP 상태, 시간, 검사를 표시합니다. 네트워크·추출 오류, 검사 실패, 2xx 이외의 응답은 실패로 처리합니다.|Prüfen Sie die Umgebung und führen Sie die ausgewählten Anfragen aus. Echte Anfragen werden einzeln gesendet. Ergebnisse zeigen HTTP-Status, Dauer und Prüfungen. Netzwerk- und Extraktionsfehler, fehlgeschlagene Prüfungen sowie Antworten außerhalb von 2xx gelten als Fehler.
Stopping prevents later requests from being sent. An in-flight request may still finish on the server. The environment is fixed when the run starts; extracted values are refreshed between requests.|停止后不会继续发送后续请求，已发送的请求仍可能在服务器上完成。运行开始时固定环境，每个请求之间会更新提取的变量值。|停止後不會繼續傳送後續請求，已傳送的請求仍可能在伺服器上完成。執行開始時固定環境，每個請求之間會更新擷取的變數值。|停止すると後続の送信を止めます。送信済みのリクエストはサーバーで完了する場合があります。環境は開始時に固定し、取得した変数はリクエスト間で更新します。|L’arrêt empêche les requêtes suivantes. Celle en cours peut encore aboutir sur le serveur. L’environnement est fixé au départ et les valeurs extraites sont actualisées entre les requêtes.|Parar impede o envio das próximas requisições. A atual pode ser concluída no servidor. O ambiente é fixado no início e os valores extraídos são atualizados entre requisições.|Detener impide enviar las siguientes solicitudes. La actual puede completarse en el servidor. El entorno queda fijado al inicio y los valores extraídos se actualizan entre solicitudes.|중지하면 후속 요청을 보내지 않습니다. 진행 중인 요청은 서버에서 완료될 수 있습니다. 환경은 시작 시 고정되며 추출된 값은 요청 사이에 갱신됩니다.|Anhalten verhindert weitere Anfragen. Eine laufende Anfrage kann auf dem Server noch abgeschlossen werden. Die Umgebung wird beim Start festgelegt, extrahierte Werte werden zwischen den Anfragen aktualisiert.
Which request is first?|哪个请求是第一个？|哪個請求是第一個？|最初のリクエストはどれ？|Quelle requête passe en premier ?|Qual requisição vem primeiro?|¿Qué solicitud va primero?|어떤 요청이 첫 번째인가요?|Welche Anfrage kommt zuerst?
Create separate HTTP requests in the same project: login, create an order, and query the order. Configure token extraction on login, use {{token}} and extract orderId on create order, then use {{orderId}} in the query URL. Use the same environment for all three. These URLs and response fields are examples; use your API's actual values.|在同一项目中创建三个独立的 HTTP 请求：登录、创建订单、查询订单。登录请求配置提取 token；创建订单使用 {{token}} 并提取 orderId；查询订单的 URL 使用 {{orderId}}。三个请求使用同一个环境。这里的 URL 和响应字段只是示例，请按实际接口填写。|在同一專案建立三個獨立的 HTTP 請求：登入、建立訂單、查詢訂單。登入設定擷取 token；建立訂單使用 {{token}} 並擷取 orderId；查詢 URL 使用 {{orderId}}。三者使用同一環境。URL 和欄位只是範例，請依實際 API 填寫。|同じプロジェクトにログイン、注文作成、注文照会の独立した HTTP リクエストを作ります。ログインで token を取得し、注文作成で {{token}} を使って orderId を取得し、照会 URL で {{orderId}} を使います。環境はすべて同じにします。URL とフィールドは例なので、実際の API に合わせてください。|Créez trois requêtes HTTP distinctes dans le même projet : connexion, création et consultation d’une commande. Extrayez token à la connexion, utilisez {{token}} et extrayez orderId à la création, puis utilisez {{orderId}} dans l’URL de consultation. Choisissez le même environnement. Adaptez les URL et champs à votre API.|Crie três requisições HTTP separadas no mesmo projeto: login, criação e consulta de pedido. Extraia token no login, use {{token}} e extraia orderId na criação, depois use {{orderId}} na URL de consulta. Use o mesmo ambiente. Adapte as URLs e campos à sua API.|Cree tres solicitudes HTTP independientes en el mismo proyecto: inicio de sesión, creación y consulta de pedido. Extraiga token al iniciar sesión, use {{token}} y extraiga orderId al crear, y use {{orderId}} en la URL de consulta. Use el mismo entorno. Adapte las URL y los campos a su API.|같은 프로젝트에 로그인, 주문 생성, 주문 조회용 HTTP 요청을 각각 만드세요. 로그인에서 token을 추출하고, 주문 생성에서 {{token}}을 사용하며 orderId를 추출한 뒤 조회 URL에 {{orderId}}를 사용하세요. 세 요청의 환경은 같아야 합니다. URL과 필드는 예시이므로 실제 API에 맞추세요.|Erstellen Sie im selben Projekt drei separate HTTP-Anfragen: Anmeldung, Bestellung erstellen und Bestellung abfragen. Extrahieren Sie token bei der Anmeldung, verwenden Sie {{token}} und extrahieren Sie orderId beim Erstellen, dann verwenden Sie {{orderId}} in der Abfrage-URL. Nutzen Sie dieselbe Umgebung. Passen Sie Beispiel-URLs und Felder an Ihre API an.
For manual sending, select login in the sidebar and tap Send first. After it succeeds and saves token, select create order and tap Send second. For batch sending, open Run Requests, select these requests, and use the up and down arrows to arrange them. The first checked row is request 1, the next checked row is request 2. Unchecked rows are skipped. The numbers beside the rows show the actual execution order.|手动发送：先在侧栏选择“登录”，点击发送；成功并保存 token 后，再选择“创建订单”，点击发送。这就是第一个、第二个请求。批量发送：打开“批量运行”，勾选这些请求，用上下箭头排序。最上面的已勾选项是第 1 个，下一个已勾选项是第 2 个；未勾选项会跳过。每行旁边的编号就是实际执行顺序。|手動傳送：先在側欄選擇登入並傳送，成功且儲存 token 後，再選擇建立訂單並傳送。批次傳送：開啟批次執行，勾選請求並用上下箭頭排序。最上方勾選項是第 1 個，下一個是第 2 個；未勾選項會略過。每行編號就是實際執行順序。|手動ではサイドバーでログインを選び、先に送信します。成功して token が保存されたら注文作成を選んで次に送信します。一括実行では対象を選び、上下矢印で並べます。最上位の選択済み行が1番、次が2番です。未選択の行は飛ばします。行の番号が実行順序です。|En manuel, sélectionnez la connexion dans la barre latérale et envoyez-la d’abord. Après réussite et enregistrement de token, envoyez la création de commande. En exécution groupée, sélectionnez les requêtes et ordonnez-les avec les flèches. La première ligne cochée est la requête 1, la suivante la 2. Les lignes décochées sont ignorées. Les numéros indiquent l’ordre réel.|No envio manual, selecione o login na barra lateral e envie primeiro. Após sucesso e gravação de token, envie a criação do pedido. Na execução em lote, selecione as requisições e ordene com as setas. A primeira linha marcada é a requisição 1, a próxima é a 2. Linhas desmarcadas são ignoradas. Os números indicam a ordem real.|Para enviar manualmente, seleccione el inicio de sesión en la barra lateral y envíelo primero. Tras guardar token correctamente, envíe la creación del pedido. En ejecución por lotes, seleccione las solicitudes y ordénelas con las flechas. La primera fila marcada es la solicitud 1, la siguiente la 2. Las filas sin marcar se omiten. Los números indican el orden real.|수동 전송은 사이드바에서 로그인을 선택해 먼저 보내세요. 성공하고 token이 저장되면 주문 생성을 선택해 두 번째로 보내세요. 일괄 실행은 요청을 선택하고 위아래 화살표로 정렬하세요. 첫 번째로 체크된 행이 요청 1, 다음이 요청 2입니다. 체크하지 않은 행은 건너뜁니다. 행의 번호가 실제 실행 순서입니다.|Senden Sie manuell zuerst die Anmeldung aus der Seitenleiste. Nach Erfolg und Speicherung von token senden Sie die Bestellung. Wählen Sie für den Stapellauf die Anfragen und ordnen Sie sie mit den Pfeilen. Die erste markierte Zeile ist Anfrage 1, die nächste Anfrage 2. Nicht markierte Zeilen werden übersprungen. Die Zahlen zeigen die tatsächliche Reihenfolge.
The numbered cards below are guide steps, not request numbers. Selecting a request in the sidebar does not make it run first. Check the batch list order each time you open the workflow panel.|下面卡片的 1、2、3 是说明步骤，不是请求编号。在侧栏选中某个请求，不会让它自动先运行。每次打开工作流面板，都请核对批量运行列表的顺序。|下方卡片的編號是說明步驟，不是請求編號。在側欄選取請求不會讓它先執行。每次開啟工作流程面板，請核對批次列表順序。|下のカード番号は説明の手順で、リクエスト番号ではありません。サイドバーで選んでも最初にはなりません。パネルを開くたびに実行リストの順序を確認してください。|Les numéros des cartes ci-dessous sont les étapes du guide. Sélectionner une requête dans la barre latérale ne la place pas en premier. Vérifiez l’ordre de la liste à chaque ouverture du panneau.|Os números dos cartões abaixo são etapas do guia. Selecionar uma requisição na barra lateral não a coloca primeiro. Confira a ordem da lista sempre que abrir o painel.|Los números de las tarjetas siguientes son pasos de la guía. Seleccionar una solicitud en la barra lateral no hace que se ejecute primero. Revise el orden de la lista al abrir el panel.|아래 카드의 번호는 설명 단계이며 요청 번호가 아닙니다. 사이드바에서 선택해도 먼저 실행되지 않습니다. 패널을 열 때마다 일괄 실행 목록의 순서를 확인하세요.|Die Kartennummern unten bezeichnen Anleitungsschritte. Eine Auswahl in der Seitenleiste macht die Anfrage nicht zur ersten. Prüfen Sie bei jedem Öffnen des Fensters die Reihenfolge der Liste.
'''

FIXUPS = {}
for row in ROWS.strip().splitlines():
    if not row.strip():
        continue
    parts = row.split('|')
    assert len(parts) == 9, parts[0]
    FIXUPS[parts[0]] = dict(zip(LANGS, parts[1:]))


def main():
    path = Path(__file__).resolve().parents[1] / 'Reqeast/Localizable.xcstrings'
    catalog = json.loads(path.read_text())
    for key, translations in FIXUPS.items():
        entry = catalog['strings'].setdefault(key, {})
        localized = entry.setdefault('localizations', {})
        for language, value in {'en': key, **translations}.items():
            localized[language] = {'stringUnit': {'state': 'translated', 'value': value}}
    path.write_text(json.dumps(catalog, ensure_ascii=False, indent=2, separators=(',', ' : ')) + '\n')


if __name__ == '__main__':
    main()
